name: Test Cron 2

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.event_name }}"
      - run: date
